### PR TITLE
Creates a sample bylaw file to be discussed.

### PR DESCRIPTION
**Pull request by naroga**
I'd like to have all the members vote here. This is a PROVISORY voting protocol, which should guide us until we have some traction and relevant community feedback.

### CODE REVIEW

**Comment by naroga** [comment]
PLEASE, DO NOT MERGE. JUST VOTE.

**Comment by hernandev** [comment]
:+1:

**Comment by pedrommone** [comment]
👍

**Comment by DennyLoko** [comment]
In a case of a poll with more than one option, how would we vote?

I would like to suggest to be comment based; where each first comments on the issue represent a single option, so we could add reactions expressing our opinion.

**Comment by hernandev** [comment]
@DennyLoko we can either support numbers or break it down to yes or no

**Comment by DennyLoko** [comment]
I suggested this approach to reduce the clutter by a lot of comments like `2 - All caps`. If we have the options as comments, we can just react to it.

**Comment by hernandev** [comment]
@naroga I would suggest accepting it as it is since no true oposition was made, we can improve It later, the  important now is the get somewhere

**Comment by hernandev** [comment]
@DennyLoko that would work
each response becomes a comment so we can react on it.

general discussion should be done on a separate issue.

**Comment by joubertredrat** [comment]
:+1: 

but in future we need to consider better options to voting like [`lgtm`](https://github.com/lgtmco/lgtm)

**Comment by naroga** [comment]
All voting members have already voted, so this vote has passed.

Summary:

Eligible voters: 7 
Quorum: 7
Voting in favor: 7
Voting against: None 
Abstaining: None 
Result: The vote has passed.

**Comment by lucasmezencio** [comment]
@naroga this was automatic? Or you wrote?

**Comment by naroga** [comment]
@lucasmezencio The summary? I wrote it, hahaha.

**Pull request merged**
